// <auto-generated />
using System;
using FCG.Games.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FCG.Games.Infrastructure.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20260731103100_AddEventStore")]
    partial class AddEventStore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("FCG.Games.Infrastructure.Events.StoredEvent", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                b.Property<string>("AggregateId").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("AggregateType").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("Data").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("EventType").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime>("OccurredAtUtc").HasColumnType("datetime2");
                b.Property<string>("TraceId").HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<int>("Version").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("OccurredAtUtc");
                b.HasIndex("AggregateType", "AggregateId", "Version").IsUnique();
                b.ToTable("StoredEvents");
            });
#pragma warning restore 612, 618
        }
    }
}
